# Generated by Django 2.2.10 on 2021-10-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Quizz',
        ),
        migrations.AlterModelOptions(
            name='quizz',
            options={'verbose_name': 'Quizz', 'verbose_name_plural': 'Quizzes'},
        ),
    ]
