# Generated by Django 2.2.10 on 2021-10-19 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='finish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='start_date',
            field=models.DateTimeField(default='2003-11-22 01:01:00'),
            preserve_default=False,
        ),
    ]
