# Generated by Django 2.2.10 on 2021-10-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Quiz',
        ),
    ]
