# Generated by Django 2.2.10 on 2021-10-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('single_choice', 'single_choice'), ('multi_choice', 'multi_choice')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
