# Generated by Django 2.2.10 on 2021-10-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20211019_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='finish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
